// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZem_ziNIv8kfuFPmtb1Lll-UeUFpAHc',
    appId: '1:343134865969:ios:8bf5d7467ae909420de310',
    messagingSenderId: '343134865969',
    projectId: 'languageapl',
    storageBucket: 'languageapl.appspot.com',
    iosClientId: '343134865969-hgl5krnger7mhb9a9mhtd8mcd7vfnjq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLanguageapplicationmycourse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZem_ziNIv8kfuFPmtb1Lll-UeUFpAHc',
    appId: '1:343134865969:ios:8bf5d7467ae909420de310',
    messagingSenderId: '343134865969',
    projectId: 'languageapl',
    storageBucket: 'languageapl.appspot.com',
    iosClientId: '343134865969-hgl5krnger7mhb9a9mhtd8mcd7vfnjq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLanguageapplicationmycourse2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1HPql7IBmMUMvFgKkThrAvXh7bCPD9eU',
    appId: '1:343134865969:web:662d7c80b23c783b0de310',
    messagingSenderId: '343134865969',
    projectId: 'languageapl',
    authDomain: 'languageapl.firebaseapp.com',
    storageBucket: 'languageapl.appspot.com',
    measurementId: 'G-MB9MQ40G17',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1HPql7IBmMUMvFgKkThrAvXh7bCPD9eU',
    appId: '1:343134865969:web:662d7c80b23c783b0de310',
    messagingSenderId: '343134865969',
    projectId: 'languageapl',
    authDomain: 'languageapl.firebaseapp.com',
    storageBucket: 'languageapl.appspot.com',
    measurementId: 'G-MB9MQ40G17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6WHmxqIAYKI_asV9lboLhxPEZD2WfnM',
    appId: '1:343134865969:android:6a3d07a714fcb87c0de310',
    messagingSenderId: '343134865969',
    projectId: 'languageapl',
    storageBucket: 'languageapl.appspot.com',
  );

}